/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace GovernanceRootPublisher {
  export type ProposalStruct = {
    id: BigNumberish;
    description: string;
    actionData: BytesLike;
    actionDataHash: BytesLike;
    snapshotBlock: BigNumberish;
    exchangeRateSnapshot: BigNumberish;
    votingPowerRoot: BytesLike;
    rootPublished: boolean;
    executed: boolean;
    createdAt: BigNumberish;
  };

  export type ProposalStructOutput = [
    id: bigint,
    description: string,
    actionData: string,
    actionDataHash: string,
    snapshotBlock: bigint,
    exchangeRateSnapshot: bigint,
    votingPowerRoot: string,
    rootPublished: boolean,
    executed: boolean,
    createdAt: bigint
  ] & {
    id: bigint;
    description: string;
    actionData: string;
    actionDataHash: string;
    snapshotBlock: bigint;
    exchangeRateSnapshot: bigint;
    votingPowerRoot: string;
    rootPublished: boolean;
    executed: boolean;
    createdAt: bigint;
  };
}

export interface GovernanceExecutorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "commitActionDataHash"
      | "committedActions"
      | "executeIfAuthorized"
      | "executedActions"
      | "getProposal"
      | "isActionExecuted"
      | "owner"
      | "renounceOwnership"
      | "rootPublisher"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ActionDataHashCommitted"
      | "ActionExecuted"
      | "OwnershipTransferred"
      | "ProposalExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "commitActionDataHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "committedActions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeIfAuthorized",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executedActions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isActionExecuted",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rootPublisher",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "commitActionDataHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "committedActions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeIfAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executedActions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isActionExecuted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rootPublisher",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ActionDataHashCommittedEvent {
  export type InputTuple = [actionDataHash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [actionDataHash: string, timestamp: bigint];
  export interface OutputObject {
    actionDataHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ActionExecutedEvent {
  export type InputTuple = [actionData: BytesLike];
  export type OutputTuple = [actionData: string];
  export interface OutputObject {
    actionData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalExecutedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    actionDataHash: BytesLike,
    actionData: BytesLike,
    executor: AddressLike
  ];
  export type OutputTuple = [
    proposalId: bigint,
    actionDataHash: string,
    actionData: string,
    executor: string
  ];
  export interface OutputObject {
    proposalId: bigint;
    actionDataHash: string;
    actionData: string;
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GovernanceExecutor extends BaseContract {
  connect(runner?: ContractRunner | null): GovernanceExecutor;
  waitForDeployment(): Promise<this>;

  interface: GovernanceExecutorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  commitActionDataHash: TypedContractMethod<
    [actionDataHash: BytesLike],
    [void],
    "nonpayable"
  >;

  committedActions: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  executeIfAuthorized: TypedContractMethod<
    [proposalId: BigNumberish, actionData: BytesLike],
    [void],
    "nonpayable"
  >;

  executedActions: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getProposal: TypedContractMethod<
    [proposalId: BigNumberish],
    [GovernanceRootPublisher.ProposalStructOutput],
    "view"
  >;

  isActionExecuted: TypedContractMethod<
    [actionDataHash: BytesLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rootPublisher: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "commitActionDataHash"
  ): TypedContractMethod<[actionDataHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "committedActions"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "executeIfAuthorized"
  ): TypedContractMethod<
    [proposalId: BigNumberish, actionData: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executedActions"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getProposal"
  ): TypedContractMethod<
    [proposalId: BigNumberish],
    [GovernanceRootPublisher.ProposalStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isActionExecuted"
  ): TypedContractMethod<[actionDataHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rootPublisher"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ActionDataHashCommitted"
  ): TypedContractEvent<
    ActionDataHashCommittedEvent.InputTuple,
    ActionDataHashCommittedEvent.OutputTuple,
    ActionDataHashCommittedEvent.OutputObject
  >;
  getEvent(
    key: "ActionExecuted"
  ): TypedContractEvent<
    ActionExecutedEvent.InputTuple,
    ActionExecutedEvent.OutputTuple,
    ActionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProposalExecuted"
  ): TypedContractEvent<
    ProposalExecutedEvent.InputTuple,
    ProposalExecutedEvent.OutputTuple,
    ProposalExecutedEvent.OutputObject
  >;

  filters: {
    "ActionDataHashCommitted(bytes32,uint256)": TypedContractEvent<
      ActionDataHashCommittedEvent.InputTuple,
      ActionDataHashCommittedEvent.OutputTuple,
      ActionDataHashCommittedEvent.OutputObject
    >;
    ActionDataHashCommitted: TypedContractEvent<
      ActionDataHashCommittedEvent.InputTuple,
      ActionDataHashCommittedEvent.OutputTuple,
      ActionDataHashCommittedEvent.OutputObject
    >;

    "ActionExecuted(bytes)": TypedContractEvent<
      ActionExecutedEvent.InputTuple,
      ActionExecutedEvent.OutputTuple,
      ActionExecutedEvent.OutputObject
    >;
    ActionExecuted: TypedContractEvent<
      ActionExecutedEvent.InputTuple,
      ActionExecutedEvent.OutputTuple,
      ActionExecutedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProposalExecuted(uint256,bytes32,bytes,address)": TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;
    ProposalExecuted: TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;
  };
}
